# Generated by Django 4.1.7 on 2023-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_addparameter_delete_fromrandomtruthtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addparameter',
            name='selection_type_parent',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип отбора родителей'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='chromosome_type',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип хромосомы'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mut_type',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип мутации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='oper_type',
            field=models.CharField(db_index=True, default=None, max_length=100, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='playback_type',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип воиспроизведения'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='selection_type',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип отбора'),
        ),
    ]
