# Generated by Django 4.1.7 on 2023-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_addparameter_selection_type_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addparameter',
            name='chromosome_type',
            field=models.CharField(choices=[('Truth Table', 'Truth Table'), ('Table 2', 'Table 2')], max_length=11, verbose_name='Тип хромосомы'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mut_type',
            field=models.CharField(choices=[('Binary', 'Binary'), ('Density', 'Density'), ('AccessionDel', 'AccessionDel'), ('IncertDel', 'IncertDel'), ('Exchange', 'Exchange'), ('Delete', 'Delete')], max_length=12, verbose_name='Тип мутации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='oper_type',
            field=models.CharField(choices=[('and', 'and'), ('nand', 'nand'), ('or', 'or'), ('not', 'not'), ('buf', 'buf'), ('xor', 'xor'), ('xnor', 'xnor')], max_length=4, verbose_name='Тип оператора'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='playback_type',
            field=models.CharField(choices=[('CrossingEachExit', 'CrossingEachExit'), ('CrossingUniform', 'CrossingUniform'), ('CrossingTriadic', 'CrossingTriadic'), ('CrossingReducedReplace', 'CrossingReducedReplace'), ('CrossingSnuffling', 'CrossingSnuffling')], max_length=22, verbose_name='Тип воиспроизведения'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='selection_type',
            field=models.CharField(choices=[('Base', 'Base'), ('Base 2', 'Base 2')], max_length=6, verbose_name='Тип отбора'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='selection_type_parent',
            field=models.CharField(choices=[('Panmixia', 'Panmixia'), ('Inbriding', 'Inbriding'), ('Otbriding', 'Otbriding'), ('Toumament', 'Toumament'), ('Roulette', 'Roulette')], max_length=9, verbose_name='Тип отбора родителей'),
        ),
    ]
