# Generated by Django 4.1.7 on 2023-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_alter_addparameter_chromosome_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addparameter',
            name='CNFF',
            field=models.BooleanField(default=0, verbose_name='CNFF'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='CNFT',
            field=models.BooleanField(default=0, verbose_name='CNFT'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='cycles',
            field=models.IntegerField(default=0, verbose_name='Количество циклов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='empty_out',
            field=models.BooleanField(default=0, verbose_name='Оставлять пустые выходы'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='limit',
            field=models.BooleanField(default=0, verbose_name='Ограничение генерации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mask_prob',
            field=models.IntegerField(default=0, verbose_name='maskProbability'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_elem',
            field=models.IntegerField(default=0, verbose_name='Максимальное количество элементов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_in',
            field=models.IntegerField(default=0, verbose_name='Максимальное количество входов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_level',
            field=models.IntegerField(default=0, verbose_name='Максимальное количество уровней'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_out',
            field=models.IntegerField(default=0, verbose_name='Максимальное количество выходов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='min_in',
            field=models.IntegerField(default=0, verbose_name='Минимальное количество входов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='min_out',
            field=models.IntegerField(default=0, verbose_name='Минимальное количество выходов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mut_chance',
            field=models.IntegerField(default=0, verbose_name='Вероятность мутации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='num',
            field=models.IntegerField(default=0, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='population',
            field=models.IntegerField(default=0, verbose_name='Размер популяции'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='ratio',
            field=models.IntegerField(default=0, verbose_name='Соотношение в таблице истинности'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='rec_num',
            field=models.IntegerField(default=0, verbose_name='recombinationNumber'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='ref_points',
            field=models.IntegerField(default=0, verbose_name='Reference points'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='repeat_n',
            field=models.IntegerField(default=0, verbose_name='Количество повторений каждой комбинации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='surv_num',
            field=models.IntegerField(default=0, verbose_name='Количество выживших'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='swap_type',
            field=models.IntegerField(default=0, verbose_name='Тип обмена'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='tour_size',
            field=models.IntegerField(default=0, verbose_name='Размер турнира'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='u_out',
            field=models.IntegerField(default=0, verbose_name='Коэффициент выхода'),
        ),
    ]
