# Generated by Django 4.1.7 on 2023-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_alter_addparameter_cnff_alter_addparameter_cnft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addparameter',
            name='type_of_generation',
            field=models.CharField(choices=[('From Random Truth Table', 'From Random Truth Table'), ('Rand Level', 'Rand Level'), ('Num Operation', 'Num Operation'), ('Genetic reproduction', 'Genetic reproduction'), ('Genetic mutation', 'Genetic mutation'), ('Genetic selection', 'Genetic selection')], default='From Random Truth Table', max_length=23, verbose_name='Метод генерации'),
        ),
    ]
