#pragma once

#include <CircuitGenGraph/GraphVertexBase.hpp>
#include <generators/simple/simple/SimpleGenerator.hpp>
#include <string_view>

namespace CG_Gen {

using namespace CG_Graph;

class ArithmeticGenerator : public SimpleGenerator {
public:
  ArithmeticGenerator();
  ArithmeticGenerator(uint_fast32_t i_seed);
  ArithmeticGenerator(const GenerationParameters &i_param);

  /// @brief generatorSummator represents the generation of a combinational
  /// adder circuit. It is based on the arithmetic operation of addition in the
  /// decimal system and creates a graph of logical elements for its
  /// implementation. The number of bits fed into it is the length of the
  /// numbers that are converted from decimal to binary notation to implement
  /// the graph. Both the half-version and the full version are used as the
  /// basis of the generation.
  /// @param i_bits The number of bits, or in other words, input vertices
  /// (variables), which will be twice as many in the graph
  /// @param i_overflowIn A Boolean flag indicating whether to create an
  /// additional input vertex (variable) in the graph at the beginning of
  /// generation
  /// @param i_overflowOut A Boolean flag indicating whether to create an
  /// additional output vertex (variable) in the graph at the end of generation
  /// @param i_minus A Boolean flag indicating whether it is worth adding
  /// logical vertices of type NOT to the graph to select a negative sum
  /// @return the created OrientedGraph

  GraphPtr generatorSummator(uint32_t i_bits, bool i_overflowIn,
                             bool i_overflowOut, bool i_minus) const;

  /// @brief generatorComparison represents the generation of a combinational
  /// comparator circuit. It is able to compare the submitted data in three
  /// variants: "equal", "less", "more". Reads the bits of numbers from larger
  /// to smaller, taking into account the significance of the higher bits.
  /// numbers that are converted from decimal to binary notation to implement
  /// the graph
  /// @param i_bits The number of bits, or in other words, input vertices
  /// (variables), which will be twice as many in the graph
  /// @param compare0 A Boolean flag indicating whether to perform the
  /// "equality" ("=") comparison operation between two bits of different
  /// numbers.
  /// @param compare1 A Boolean flag indicating indicating whether to perform
  /// the "less" ("<") comparison operation between two bits of different
  /// numbers.
  /// @param compare2 A Boolean flag indicating indicating whether to perform
  /// the "more" (">") comparison operation between two bits of different
  /// numbers.
  /// @return the created OrientedGraph

  GraphPtr generatorSubtractor(uint32_t i_bits, bool i_overflowIn,
                               bool i_overflowOut, bool i_sub);

  GraphPtr generatorMultiplier(uint32_t i_bits);

  GraphPtr generatorSummator(const GenerationParameters &i_param) const;
  /**
 * @brief Generates a bus-level wrapper for the bit-level ripple-carry
 * summator graph.
 *
 * The method creates two input buses and one output bus, slices the input buses
 * into single-bit signals, connects them to the bit-level summator generated by
 * generatorSummator(), and concatenates the bit-level sum outputs back into the
 * output bus.
 *
 * Input buses:
 * - busX: first operand, width i_bits.
 * - busY: second operand, width i_bits.
 *
 * Input connection order to the internal summator subgraph:
 * - busX[0]
 * - busY[0]
 * - overflowIn, only if i_overflowIn == true
 * - busX[1]
 * - busY[1]
 * - ...
 * - busX[i_bits - 1]
 * - busY[i_bits - 1]
 *
 * Output buses:
 * - sum: result bus, width i_bits.
 *
 * Additional outputs:
 * - overflowOut, only if i_overflowOut == true.
 *
 * Internal subgraph output order is expected to be:
 * - sum[0], sum[1], ..., sum[i_bits - 1]
 * - overflowOut, only if i_overflowOut == true.
 *
 * @param i_bits Width of both input operands and the sum output bus.
 * @param i_overflowIn Enables an additional input carry signal.
 * @param i_overflowOut Enables an additional output carry signal.
 * @param i_minus Enables subtraction mode in the underlying summator.
 * @return Graph containing bus-level inputs/outputs and the connected summator
 * subgraph.
 */
  GraphPtr generatorBusSummator(uint32_t i_bits, bool i_overflowIn,
                             bool i_overflowOut, bool i_minus, std::string_view i_name = "") const;

  GraphPtr generatorSubtractor(const GenerationParameters &i_param);
  /**
 * @brief Generates a bus-level wrapper for the bit-level subtractor graph.
 *
 * The method creates two input buses and one output bus, slices the input buses
 * into single-bit signals, connects them to the bit-level subtractor generated
 * by generatorSubtractor(), and concatenates the bit-level difference outputs
 * back into the output bus.
 *
 * Input buses:
 * - busX: first operand, width i_bits.
 * - busY: second operand, width i_bits.
 *
 * Input connection order to the internal subtractor subgraph:
 * - busX[0]
 * - busY[0]
 * - overflowIn, only if i_overflowIn == true
 * - busX[1]
 * - busY[1]
 * - ...
 * - busX[i_bits - 1]
 * - busY[i_bits - 1]
 *
 * Output buses:
 * - diff: difference output bus, width i_bits.
 *
 * Additional outputs:
 * - overflowOut, only if i_overflowOut == true.
 *
 * Internal subgraph output order is expected to be:
 * - diff[0], diff[1], ..., diff[i_bits - 1]
 * - overflowOut, only if i_overflowOut == true.
 *
 * @param i_bits Width of both input operands and the difference output bus.
 * @param i_overflowIn Enables an additional input borrow signal.
 * @param i_overflowOut Enables an additional output borrow signal.
 * @param i_sub Selects the subtraction direction in the underlying subtractor.
 * If false, the underlying subtractor computes busX - busY. If true, it computes
 * busY - busX, according to generatorSubtractor() semantics.
 * @return Graph containing bus-level inputs/outputs and the connected
 * subtractor subgraph.
 */
  GraphPtr generatorBusSubtractor(
    uint32_t i_bits,
    bool i_overflowIn,
    bool i_overflowOut,
    bool i_sub,
    std::string_view i_name = ""
);

  GraphPtr generatorMultiplier(const GenerationParameters &i_param);
  /**
 * @brief Generates a bus-level wrapper for the bit-level multiplier graph.
 *
 * The method creates two input buses and one output bus, slices the input buses
 * into single-bit signals, connects them to the bit-level multiplier generated
 * by generatorMultiplier(), and concatenates the bit-level product outputs back
 * into the output bus.
 *
 * Input buses:
 * - busX: first multiplier operand, width i_bits.
 * - busY: second multiplier operand, width i_bits.
 *
 * Input connection order to the internal multiplier subgraph:
 * - busY[0]
 * - busX[0]
 * - busY[1]
 * - busX[1]
 * - ...
 * - busY[i_bits - 1]
 * - busX[i_bits - 1]
 *
 * This order matches the input creation order of generatorMultiplier(), where
 * each bit pair is created as xbN followed by xaN.
 *
 * Output buses:
 * - mul: product output bus, width 2 * i_bits.
 *
 * Internal subgraph output order is expected to be:
 * - mul[0], mul[1], ..., mul[2 * i_bits - 1].
 *
 * @param i_bits Width of both multiplier operands.
 * @return Graph containing bus-level inputs/outputs and the connected
 * multiplier subgraph.
 */
  GraphPtr generatorBusMultiplier(uint32_t i_bits, std::string_view i_name = "");

  GraphPtr generateNonRestoringDiv(const GenerationParameters &i_param) const;
  /**
 * @brief Generates a bus-level wrapper for the non-restoring divider graph.
 *
 * The method creates two input buses and one output bus, slices the input buses
 * into single-bit signals, connects them to the bit-level divider generated by
 * generateNonRestoringDiv(), and concatenates the bit-level quotient outputs
 * back into the output bus.
 *
 * Input buses:
 * - busA: dividend input bus, width sizeA.
 * - busB: divisor input bus, width sizeB.
 *
 * Input connection order to the internal divider subgraph:
 * - busA[0]
 * - busA[1]
 * - ...
 * - busA[sizeA - 1]
 * - busB[0]
 * - busB[1]
 * - ...
 * - busB[sizeB - 1]
 *
 * This order matches the input creation order of generateNonRestoringDiv(),
 * where all dividend bits are created first and all divisor bits are created
 * after them.
 *
 * Output buses:
 * - quotient: quotient output bus, width sizeY.
 *
 * Internal subgraph output order is expected to be:
 * - quotient[0], quotient[1], ..., quotient[sizeY - 1].
 *
 * @param sizeA Width of the dividend input bus.
 * @param sizeB Width of the divisor input bus.
 * @param sizeY Width of the quotient output bus.
 * @param useSign Enables signed division handling in the underlying divider.
 * @return Graph containing bus-level inputs/outputs and the connected
 * non-restoring divider subgraph.
 */
  GraphPtr generatorBusNonRestoringDiv(
    size_t sizeA,
    size_t sizeB,
    size_t sizeY,
    bool useSign,
    std::string_view i_name = ""
) const;

  GraphPtr generateNonRestoringDiv(
    size_t sizeA, size_t sizeB, size_t sizeY, bool useSign) const;

  GraphPtr generateIncrement(const GenerationParameters &i_param) const;

  GraphPtr generateDecrement(const GenerationParameters &i_param) const;

  GraphPtr
  generateAdvancedArithmetic(const GenerationParameters &i_param) const;

  GraphPtr generatorSummator();

  GraphPtr generatorSubtractor();

  GraphPtr generatorMultiplier();

  GraphPtr generateWallaceTree(size_t i_argsCount, size_t bits, ArithemticOperations::Types summatorType) const;

  GraphPtr generateAdvancedArithmetic() const;
};

} // namespace CG_Gen
