ARG system="registry-hub.mos.ru/circuitgen/circuitgen_graph:ci_latest"

FROM ${system}

RUN apt-get update && \
  apt-get upgrade -y

RUN apt-get update && apt-get install -y \
  gdb \
  nano \
  sudo \
  vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /circuitgen
RUN chown -R $USERNAME:$USERNAME /circuitgen

WORKDIR /circuitgen/graph

COPY . .

RUN echo '{ \
  "version": 2, \
  "cmakeMinimumRequired": { \
  "major": 3, \
  "minor": 14, \
  "patch": 0 \
  }, \
  "configurePresets": [ \
  { \
  "name": "dev", \
  "binaryDir": "${sourceDir}/build/dev", \
  "inherits": ["dev-mode", "ci-linux"], \
  "cacheVariables": { \
  "CMAKE_BUILD_TYPE": "Debug" \
  } \
  } \
  ], \
  "buildPresets": [ \
  { \
  "name": "dev", \
  "configurePreset": "dev", \
  "configuration": "Debug" \
  } \
  ], \
  "testPresets": [ \
  { \
  "name": "dev", \
  "configurePreset": "dev", \
  "configuration": "Debug", \
  "output": { \
  "outputOnFailure": true \
  } \
  } \
  ] \
  }' > /circuitgen/graph/CMakeUserPresets.json


USER $USERNAME

ENV PATH="/usr/local/bin:$PATH"
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
