#!/bin/bash
cd Generator/source
mkdir build
cd build
cmake ..
make
cd ../../../
gdb --args Generator/source/build/prog --json_path=/home/rustam/1290_project/Generator/source/test_data/wast/sample.json
