# Generated by Django 4.1.7 on 2023-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_parameter', '0006_addparameter_type_of_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addparameter',
            old_name='empty_out',
            new_name='leave_empty_out',
        ),
        migrations.RenameField(
            model_name='addparameter',
            old_name='population',
            new_name='population_size',
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='num',
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='oper_type',
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='u_out',
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_and',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_buf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_nand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_nor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_not',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_or',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_xnor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='num_xor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='out_ratio',
            field=models.FloatField(default=0, verbose_name='Коэффициент выхода'),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='ratio_in_table',
            field=models.FloatField(default=0, verbose_name='Соотношение в таблице истинности'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='chromosome_type',
            field=models.CharField(choices=[('Truth Table', 'Truth Table'), ('Other', 'Other')], max_length=11, verbose_name='Тип хромосомы'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mask_prob',
            field=models.FloatField(default=0, verbose_name='maskProbability'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_in',
            field=models.IntegerField(default=1, verbose_name='Максимальное количество входов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_level',
            field=models.IntegerField(default=1, verbose_name='Максимальное количество уровней'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='max_out',
            field=models.IntegerField(default=1, verbose_name='Максимальное количество выходов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='min_in',
            field=models.IntegerField(default=1, verbose_name='Минимальное количество входов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='min_out',
            field=models.IntegerField(default=1, verbose_name='Минимальное количество выходов'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='mut_chance',
            field=models.FloatField(default=0, verbose_name='Вероятность мутации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='repeat_n',
            field=models.IntegerField(default=1, verbose_name='Количество повторений каждой комбинации'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='selection_type',
            field=models.CharField(choices=[('Base', 'Base'), ('Other', 'Other')], max_length=6, verbose_name='Тип отбора'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='swap_type',
            field=models.CharField(choices=[('Cell Above', 0), ('Cell Right', 1), ('Four Cells', 2), ('String Above', 3)], max_length=12, verbose_name='Тип обмена'),
        ),
    ]
