# Generated by Django 4.1.7 on 2023-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_parameter', '0008_alter_addparameter_swap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addparameter',
            name='playback_type',
            field=models.CharField(choices=[('CrossingEachExitInTurnMany', 'CrossingEachExitInTurnMany'), ('CrossingUniform', 'CrossingUniform'), ('CrossingTriadic', 'CrossingTriadic'), ('CrossingReducedReplace', 'CrossingReducedReplace'), ('CrossingSnuffling', 'CrossingSnuffling')], max_length=28, verbose_name='Тип воиспроизведения'),
        ),
        migrations.AlterField(
            model_name='addparameter',
            name='selection_type_parent',
            field=models.CharField(choices=[('Panmixia', 'Panmixia'), ('Inbriding', 'Inbriding'), ('Otbriding', 'Otbriding'), ('Tournament', 'Tournament'), ('Roulette', 'Roulette')], max_length=10, verbose_name='Тип отбора родителей'),
        ),
    ]
