# Generated by Django 4.1.7 on 2023-03-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FromRandomTruthTable',
        ),
        migrations.DeleteModel(
            name='GeneticMutation',
        ),
        migrations.DeleteModel(
            name='GeneticPlayback',
        ),
        migrations.DeleteModel(
            name='GeneticSelection',
        ),
        migrations.DeleteModel(
            name='NumOperations',
        ),
        migrations.DeleteModel(
            name='RandLevel',
        ),
    ]
