#include "ChiselProject.hpp"

#include <regex>
#include <sys/wait.h>
#include <unistd.h>

namespace CG_Gen {

ChiselProject::ChiselProject(const std::filesystem::path &i_baseDir,
                             const std::filesystem::path &i_tempDirPath,
                             const std::filesystem::path &i_outputDir,
                             const std::filesystem::path &i_inputFile) :
    d_baseDir(i_baseDir), d_tempDirPath(i_tempDirPath),
    d_outputDir(i_outputDir), d_tempProject(d_tempDirPath, d_baseDir) {

  if (!std::filesystem::exists(i_baseDir) || !i_baseDir.is_absolute()) {
    throw std::runtime_error("Wrong base directory path");
  }

  if (i_tempDirPath.empty()) {
    throw std::runtime_error("Empty temporary directory path");
  }

  if (i_inputFile.empty() || !std::filesystem::exists(i_inputFile)) {
    throw std::runtime_error("No such file or wrong filename: " +
                             i_inputFile.string());
  }

  if (d_outputDir.empty()) {
    throw std::runtime_error("Output directory path is empty");
  }

  if (!std::filesystem::exists(d_outputDir) &&
      !std::filesystem::create_directories(d_outputDir)) {
    throw std::runtime_error("Cannot create output directory: " +
                             d_outputDir.string());
  }

  std::filesystem::path destDir = d_tempDirPath / i_inputFile.filename();

  d_tempProject.copyFile(makeAbsolutePath(i_inputFile), destDir);
  std::filesystem::path copiedFilePath = d_tempDirPath / i_inputFile.filename();

  if (ifMainInInput(i_inputFile)) {
    d_mainObject = adaptMainModule(copiedFilePath, d_outputDir);
  } else {
    d_mainObject = createMainModule(copiedFilePath, d_outputDir);
  }

  if (d_mainObject.empty()) {
    throw std::runtime_error("Error occurred with executable .scala file");
  }

  std::filesystem::path buildFile = createBuildFile(d_tempDirPath);

  if (buildFile.empty() || !std::filesystem::exists(buildFile)) {
    throw std::runtime_error("Error occurred with build.sbt file: " +
                             buildFile.string());
  }
}

std::filesystem::path ChiselProject::makeAbsolutePath(
    const std::filesystem::path &i_relativePath) const {
  if (i_relativePath.is_absolute()) {
    return i_relativePath.lexically_normal();
  }
  return std::filesystem::absolute(i_relativePath).lexically_normal();
}

bool ChiselProject::ifMainInInput(
    const std::filesystem::path &i_inputFile) const {
  if (i_inputFile.empty() || !std::filesystem::exists(i_inputFile)) {
    std::cerr << "No such file or wrong file name: " << i_inputFile.string()
              << std::endl;
    return false;
  }

  std::ifstream file(i_inputFile);
  if (!file.is_open()) {
    std::cerr << "Unable to open file: " << i_inputFile.string() << std::endl;
    return false;
  }

  std::vector<std::regex> patterns = {
      std::regex(R"(object\s+\w+\s+extends\s+App)"),
      std::regex(R"(object\s+\w+\s+extends\s+App\s*\{)"),
      std::regex(R"(object\s+\w+\s*\{[^}]*def\s+main\s*\()"),
  };

  std::string line;
  int lineNumber = 0;

  while (std::getline(file, line)) {
    lineNumber++;

    size_t commentPos = line.find("//");
    if (commentPos != std::string::npos) {
      line = line.substr(0, commentPos);
    }

    for (const auto &pattern: patterns) {
      if (std::regex_search(line, pattern)) {
        return true;
      }
    }
  }

  if (file.bad()) {
    std::cerr << "Error of file reading: " << i_inputFile.string() << std::endl;
    return false;
  }

  file.close();
  return false;
}

std::string ChiselProject::createMainModule(
    const std::filesystem::path &i_inputFile,
    const std::filesystem::path &i_outputPath) const {
  if (i_inputFile.empty() || !std::filesystem::exists(i_inputFile)) {
    std::cerr << "No such file or wrong file name: " << i_inputFile.string()
              << std::endl;
    return "";
  }

  auto modules = findAllModules(i_inputFile);
  if (modules.size() == 0) {
    std::cerr << "Error occurred during file reading: " << i_inputFile.string()
              << std::endl;
    return "";
  }

  if (hasAnyParameterizedModules(modules)) {
    std::cerr
        << "There are parmeterized modules in description, which is unavailable"
        << std::endl;
    return "";
  }

  std::filesystem::path absoluteOutputDir = makeAbsolutePath(i_outputPath);
  std::filesystem::path mainFile =
      i_inputFile.parent_path() / "AutoGeneratedMain.scala";
  std::ofstream out(mainFile);

  if (!out.is_open()) {
    std::cerr << "Error: Cannot create file" << std::endl;
    return "";
  }

  out << "// AUTO-GENERATED MAIN\n";
  out << "import chisel3._\n";
  out << "import circt.stage.ChiselStage\n\n";

  out << "object AutoGeneratedMain extends App {\n";

  for (const auto &module: modules) {
    out << "    ChiselStage.emitSystemVerilogFile(new " << module.d_name
        << "(),\n";
    out << "        Array(\"--target-dir\", \"" << absoluteOutputDir.string()
        << "\")\n";
    out << "    )\n\n";
  }

  out << "}\n";

  out.close();

  std::string mainObject = "AutoGeneratedMain";

  return mainObject;
}

bool ChiselProject::hasAnyParameterizedModules(
    std::vector<ModuleInfo> &i_modules) const {
  for (const auto &module: i_modules) {
    if (module.d_hasParams) {
      return true;
    }
  }
  return false;
}

std::vector<ModuleInfo>
ChiselProject::findAllModules(const std::filesystem::path &i_inputFile) const {
  std::vector<ModuleInfo> modules;

  if (i_inputFile.empty() || !std::filesystem::exists(i_inputFile)) {
    std::cerr << "No such file or wrong file name: " << i_inputFile.string()
              << std::endl;
    return modules;
  }

  std::ifstream file(i_inputFile);
  if (!file.is_open()) {
    std::cerr << "Unable to open file: " << i_inputFile.string() << std::endl;
    return modules;
  }

  std::string line;
  std::regex moduleWithParams(
      R"(class\s+(\w+)\s*\([^)]*\)\s+extends\s+Module)");
  std::regex moduleWithoutParams(R"(class\s+(\w+)\s+extends\s+Module)");

  while (std::getline(file, line)) {
    size_t commentPos = line.find("//");
    if (commentPos != std::string::npos) {
      line = line.substr(0, commentPos);
    }

    std::smatch match;

    if (std::regex_search(line, match, moduleWithParams)) {
      modules.push_back({match[1], true});
    } else if (std::regex_search(line, match, moduleWithoutParams)) {
      modules.push_back({match[1], false});
    }
  }

  file.close();
  return modules;
}

std::string ChiselProject::adaptMainModule(
    const std::filesystem::path &i_inputFile,
    const std::filesystem::path &i_outputPath) const {

  if (i_inputFile.empty() || !std::filesystem::exists(i_inputFile)) {
    std::cerr << "No such file or wrong file name: " << i_inputFile.string()
              << std::endl;
    return "";
  }

  std::ifstream inFile(i_inputFile);
  if (!inFile.is_open()) {
    std::cerr << "Error: Cannot open file: " << i_inputFile << std::endl;
    return "";
  }

  std::stringstream buffer;
  buffer << inFile.rdbuf();
  std::string content = buffer.str();
  inFile.close();

  std::filesystem::path absoluteOutputDir = makeAbsolutePath(i_outputPath);
  std::string absoluteOutputDirStr = absoluteOutputDir.string();

  std::string modifiedContent = content;
  std::string mainObject = "";

  std::regex appPattern(R"(object\s+(\w+)\s+extends\s+App)");
  std::regex objectWithMainPattern(
      R"(object\s+(\w+)\s*\{[^}]*def\s+main\s*\()");

  std::smatch mainObjectMatch;
  if (std::regex_search(content, mainObjectMatch, appPattern)) {
    mainObject = mainObjectMatch[1];
  } else if (std::regex_search(content, mainObjectMatch,
                               objectWithMainPattern)) {
    mainObject = mainObjectMatch[1];
  }

  std::regex emitVerilogCIRCT(
      R"(circt\.stage\.ChiselStage\s*\.\s*emitSystemVerilog\s*\(\s*new\s+(\w+))");

  std::regex emitVerilogUniversal(
      R"((?:ChiselStage|chisel3\.stage\.ChiselStage|Driver|)"
      R"(\(new\s+ChiselStage\))\s*\.\s*(?:emitSystemVerilog|emitVerilog|emitFirrtl|execute)\s*[\(\{]\s*)"
      R"((?:\(\)\s*=>\s*)?\s*new\s+(\w+))");

  std::regex targetDirPattern(R"(--target-dir\",\s*\"[^\"]*\")");

  std::smatch match;

  if (std::regex_search(modifiedContent, match, emitVerilogCIRCT)) {
    std::string moduleName = match[1];

    if (std::regex_search(modifiedContent, targetDirPattern)) {
      modifiedContent = std::regex_replace(modifiedContent, targetDirPattern,
                                           "--target-dir\", \"" +
                                               absoluteOutputDirStr + "\"");
    } else {
      std::regex insertPattern(R"(new\s+)" + moduleName + R"(\s*\(\)\s*\))");
      modifiedContent = std::regex_replace(
          modifiedContent, insertPattern,
          "new " + moduleName + "(), Array(\"--target-dir\", \"" +
              absoluteOutputDirStr + "\")");
    }
  } else if (std::regex_search(modifiedContent, match, emitVerilogUniversal)) {
    std::string moduleName = match[1];

    if (std::regex_search(modifiedContent, targetDirPattern)) {
      modifiedContent = std::regex_replace(modifiedContent, targetDirPattern,
                                           "--target-dir\", \"" +
                                               absoluteOutputDirStr + "\"");
    } else {
      std::regex insertPattern(R"((new\s+)" + moduleName + R"(\s*\(\)))");
      modifiedContent = std::regex_replace(modifiedContent, insertPattern,
                                           "$1, Array(\"--target-dir\", \"" +
                                               absoluteOutputDirStr + "\")");
    }
  }

  if (modifiedContent == content) {
    std::cerr << "Warning! Main module was not modified - might lead to a "
                 "fault during compilation"
              << std::endl;
    return "";
  }

  std::ofstream file(i_inputFile);
  if (!file.is_open()) {
    std::cerr << "Error: Cannot open file: " << i_inputFile << std::endl;
    return "";
  }

  file << modifiedContent;
  file.close();

  return mainObject;
}

bool ChiselProject::checkPackages() {
  if (system("java -version > /dev/null 2>&1") != 0) {
    return false;
  }

  if (system("sbt --version > /dev/null 2>&1") != 0) {
    return false;
  }

  return true;
}

bool ChiselProject::createVerilog() {
  if (!checkPackages()) {
    std::cerr << "Error: Problem with packages" << std::endl;
    return false;
  }

  pid_t pid = fork();
  if (pid == -1) {
    std::cerr << "Error: failed to fork process" << std::endl;
    return false;
  }

  if (pid == 0) {
    if (chdir(d_tempDirPath.string().c_str()) != 0) {
      std::cerr << "Error: failed to change working directory" << std::endl;
      return false;
    }

    std::string runMain = "runMain " + d_mainObject;
    execlp("sbt", "sbt", "-error", runMain.c_str(), nullptr);

    std::cerr << "Error: failed to execute sbt" << std::endl;
    return false;
  }

  int statusCode;

  if (waitpid(pid, &statusCode, 0) == -1) {
    std::cerr << "Error: failed to wait child process" << std::endl;
    return false;
  }

  if (WIFEXITED(statusCode)) {
    int exitCode = WEXITSTATUS(statusCode);
    if (exitCode != 0) {
      std::cerr << "Error: SBT execution failed. Exit code: " << exitCode
                << std::endl;
      return false;
    }
  } else {
    std::cerr << "Error: SBT process terminated unsuccessfully" << std::endl;
    return false;
  }

  return true;
}

std::filesystem::path
ChiselProject::createBuildFile(const std::filesystem::path &i_projectDir,
                               const std::string &i_scalaVersion,
                               const std::string &i_chiselVersion) const {
  std::filesystem::path buildSbtPath = i_projectDir / "build.sbt";

  std::ofstream file(buildSbtPath);
  if (!file.is_open()) {
    std::cerr << "Error: Cannot open file: " << buildSbtPath.string()
              << std::endl;
    return "";
  }

  file << "// Auto-generated build.sbt for Chisel project\n";

  file << "// Project settings\n";
  file << "name := \"chisel-project\"\n";
  file << "version := \"1.0\"\n";
  file << "scalaVersion := \"" << i_scalaVersion << "\"\n\n";
  file << "addCompilerPlugin(\"org.chipsalliance\" %% \"chisel-plugin\" % \""
       << i_chiselVersion << "\" cross CrossVersion.full)\n\n";

  file << "// Core dependencies\n";
  file << "libraryDependencies ++= Seq(\n";
  file << "  \"org.chipsalliance\" %% \"chisel\" % \"" << i_chiselVersion
       << "\",\n";
  file << "  \"edu.berkeley.cs\" %% \"chiseltest\" % \"0.6.0\" % Test\n";
  file << ")\n\n";

  file << "// Scala compiler options\n";
  file << "scalacOptions ++= Seq(\n";
  file << "  \"-language:reflectiveCalls\",\n";
  file << "  \"-deprecation\",\n";
  file << "  \"-feature\",\n";
  file << "  \"-Xcheckinit\"\n";
  file << ")\n";

  file.close();

  return buildSbtPath;
}

void ChiselProject::cleanGeneratedFiles(
    const std::filesystem::path &i_outputPath) {
  std::regex firPattern(R"(.*\.fir$)");
  std::regex annoPattern(R"(.*\.anno\.json$)");
  for (const auto &entry: std::filesystem::directory_iterator(i_outputPath)) {
    std::string filename = entry.path().filename().string();

    if (std::regex_match(filename, firPattern) ||
        std::regex_match(filename, annoPattern)) {
      std::filesystem::remove(entry.path());
    }
  }
}
} // namespace CG_Gen