#include <gtest/gtest.h>

#include "chiselModule/ChiselProject.hpp"
#include "easylogging++Init.hpp"
#include "fstream"
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <getopt.h>
#include <regex>
#include <vector>

using namespace CG_Gen;

const std::filesystem::path currentDirectory =
    std::filesystem::current_path() / "src" / "chiselModule";
const std::filesystem::path outputPath =
    currentDirectory / "testData_ChiselModule";

struct ParsedArgs {
  bool isChisel = false;
  std::string chiselPath;
  std::string jsonPath;
};

ParsedArgs parseArgs(int argc, char **argv) {
  optind = 1;
  optopt = 0;
  opterr = 0;

  ParsedArgs result;

  const char *const short_opts = "j:n:c:";
  const option long_opts[] = {{"json_path", required_argument, nullptr, 'j'},
                              {"num_nodes", required_argument, nullptr, 'n'},
                              {"chisel_path", required_argument, nullptr, 'c'}};
  int32_t opt;
  while ((opt = getopt_long(argc, argv, short_opts, long_opts, nullptr)) !=
         -1) {
    switch (opt) {
      case 'j':
        result.jsonPath = optarg;
        break;
      case 'c':
        result.chiselPath = optarg;
        result.isChisel = true;
        break;
    }
  }

  return result;
}

std::filesystem::path getUniqueTempDir() {
  auto timestamp =
      std::chrono::duration_cast<std::chrono::nanoseconds>(
          std::chrono::high_resolution_clock::now().time_since_epoch())
          .count();
  return currentDirectory / ("testTempDir_" + std::to_string(timestamp) + "_" +
                             std::to_string(rand()));
}

bool chiselToolchainAvailable() {
  return std::system("java -version >/dev/null 2>&1") == 0 &&
         std::system("sbt --version >/dev/null 2>&1") == 0;
}

TEST(ChiselProject, checkPackagesTest) {
  if (!chiselToolchainAvailable()) {
    GTEST_SKIP() << "java/sbt toolchain not available";
  }

  std::filesystem::path tempDirectory = getUniqueTempDir();

  std::filesystem::path inputPath =
      currentDirectory / "testData_ChiselModule" / "no_main.scala";

  auto chiselProject = std::make_unique<ChiselProject>(
      currentDirectory, tempDirectory, outputPath, inputPath);

  ASSERT_TRUE(chiselProject->checkPackages());
}

TEST(ChiselProject, noMainModuleTest) {
  std::filesystem::path tempDirectory = getUniqueTempDir();
  std::filesystem::path inputPath =
      currentDirectory / "testData_ChiselModule" / "no_main.scala";

  auto chiselProject = std::make_unique<ChiselProject>(
      currentDirectory, tempDirectory, outputPath, inputPath);

  bool hasBuildFile = false;
  if (!std::filesystem::exists(tempDirectory) ||
      !std::filesystem::is_directory(tempDirectory)) {
    hasBuildFile = false;
  }

  for (const auto &entry: std::filesystem::directory_iterator(tempDirectory)) {
    if (entry.is_regular_file() && entry.path().extension() == ".sbt") {
      hasBuildFile = true;
      break;
    }
  }
  EXPECT_TRUE(hasBuildFile);

  std::filesystem::path targetModule =
      tempDirectory / "AutoGeneratedMain.scala";
  std::ifstream file(targetModule);
  bool check = false;
  if (file.is_open()) {
    std::string content;
    std::stringstream buffer;
    buffer << file.rdbuf();
    content = buffer.str();
    size_t pos = content.find("AutoGeneratedMain");
    if (pos != std::string::npos) {
      check = true;
    }
  }
  file.close();
  EXPECT_TRUE(check);
}

TEST(ChiselProject, WithMainModuleTest) {
  std::filesystem::path tempDirectory = getUniqueTempDir();
  std::filesystem::path inputPath =
      currentDirectory / "testData_ChiselModule" / "with_main.scala";

  auto chiselProject = std::make_unique<ChiselProject>(
      currentDirectory, tempDirectory, outputPath, inputPath);

  bool hasBuildFile = false;
  if (!std::filesystem::exists(tempDirectory) ||
      !std::filesystem::is_directory(tempDirectory)) {
    hasBuildFile = false;
  }

  for (const auto &entry: std::filesystem::directory_iterator(tempDirectory)) {
    if (entry.is_regular_file() && entry.path().extension() == ".sbt") {
      hasBuildFile = true;
      break;
    }
  }
  EXPECT_TRUE(hasBuildFile);

  std::filesystem::path targetModule = tempDirectory / "with_main.scala";
  std::ifstream file(targetModule);
  bool check;
  if (file.is_open()) {
    std::string content;
    std::stringstream buffer;
    buffer << file.rdbuf();
    content = buffer.str();
    size_t pos = content.find(outputPath.string());
    if (pos != std::string::npos) {
      check = true;
    }
  }
  file.close();
  EXPECT_TRUE(check);
}

TEST(ChiselProject, createVerilogTest) {
  if (!chiselToolchainAvailable()) {
    GTEST_SKIP() << "java/sbt toolchain not available";
  }

  std::filesystem::path tempDirectory = getUniqueTempDir();
  std::filesystem::path inputPath =
      currentDirectory / "testData_ChiselModule" / "no_main.scala";

  auto chiselProject = std::make_unique<ChiselProject>(
      currentDirectory, tempDirectory, outputPath, inputPath);

  bool result = chiselProject->createVerilog();
  EXPECT_TRUE(result);

  bool hasVerilog = false;
  if (!std::filesystem::exists(outputPath) ||
      !std::filesystem::is_directory(outputPath)) {
    hasVerilog = false;
  }

  for (const auto &entry: std::filesystem::directory_iterator(outputPath)) {
    if (entry.is_regular_file() && (entry.path().extension() == ".v" ||
                                    entry.path().extension() == ".sv")) {
      hasVerilog = true;
      break;
    }
  }
  EXPECT_TRUE(hasVerilog);
}

TEST(ChiselProject, validateAutogeneratedMain) {
  std::filesystem::path tempDirectory = getUniqueTempDir();
  std::filesystem::path inputPath =
      currentDirectory / "testData_ChiselModule" / "no_main.scala";

  auto chiselProject = std::make_unique<ChiselProject>(
      currentDirectory, tempDirectory, outputPath, inputPath);

  std::filesystem::path mainModule = tempDirectory / "AutoGeneratedMain.scala";

  std::ifstream file(mainModule);
  bool validSyntax = false;

  if (file.is_open()) {
    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string content = buffer.str();
    file.close();

    std::regex mainObjectPattern(
        R"(object\s+AutoGeneratedMain\s+extends\s+App\s*\{)");
    if (!std::regex_search(content, mainObjectPattern)) {
      validSyntax = false;
    }

    std::regex targetDirPattern(R"(Array\(\"--target-dir\",\s*\"([^\"]*)\"\))");
    std::smatch match;
    std::string::const_iterator searchStart(content.cbegin());
    int targetDirCount = 0;
    bool allPathsValid = true;

    while (std::regex_search(searchStart, content.cend(), match,
                             targetDirPattern)) {
      targetDirCount++;
      std::string path = match[1].str();

      if (path.empty()) {
        allPathsValid = false;
        break;
      }

      if (path[0] != '/') {
        allPathsValid = false;
        break;
      }

      if (path.find('"') != std::string::npos) {
        allPathsValid = false;
        break;
      }

      searchStart = match.suffix().first;
    }

    if (targetDirCount > 0 && allPathsValid) {
      validSyntax = true;
    } else {
      validSyntax = false;
    }
  }

  EXPECT_TRUE(validSyntax);
}

TEST(ChiselProject, shortOptionParsingTest) {
  std::vector<char *> argv = {const_cast<char *>("./build/CircuitGenGenerator"),
                              const_cast<char *>("-c"),
                              const_cast<char *>("/path/to/file.scala")};
  int argc = 3;

  ParsedArgs result = parseArgs(argc, argv.data());
  EXPECT_TRUE(result.isChisel);
  EXPECT_EQ(result.chiselPath, "/path/to/file.scala");
}

TEST(ChiselProject, longOptionParsingTest) {
  std::vector<char *> argv = {const_cast<char *>("./build/CircuitGenGenerator"),
                              const_cast<char *>("--chisel_path"),
                              const_cast<char *>("/path/to/file.scala")};
  int argc = 3;

  ParsedArgs result = parseArgs(argc, argv.data());
  EXPECT_TRUE(result.isChisel);
  EXPECT_EQ(result.chiselPath, "/path/to/file.scala");
}
