# Задание основных параметров при генерации визуализации зависимостей CMake в DOT файл

set(GRAPHVIZ_GRAPH_NAME           "${CMAKE_PROJECT_NAME}")
set(GRAPHVIZ_GRAPH_HEADER         "node [ fontsize = \"14\" ];")
set(GRAPHVIZ_NODE_PREFIX          "node")
set(GRAPHVIZ_EXECUTABLES          TRUE)
set(GRAPHVIZ_STATIC_LIBS          TRUE)
set(GRAPHVIZ_SHARED_LIBS          TRUE)
set(GRAPHVIZ_MODULE_LIBS          TRUE)
set(GRAPHVIZ_INTERFACE_LIBS       TRUE)
set(GRAPHVIZ_OBJECT_LIBS          TRUE)
set(GRAPHVIZ_UNKNOWN_LIBS         TRUE)
set(GRAPHVIZ_EXTERNAL_LIBS        TRUE)
set(GRAPHVIZ_CUSTOM_TARGETS       FALSE)
set(GRAPHVIZ_IGNORE_TARGETS       "CircuitGenGenerator_tests;CircuitGenGenerator_test_*")
set(GRAPHVIZ_GENERATE_PER_TARGET  TRUE)
set(GRAPHVIZ_GENERATE_DEPENDERS   TRUE)
