include("${CMAKE_CURRENT_LIST_DIR}/colors.cmake")
define_colors()
set(default_output_max_len 80)

function(print_as_title arg1) # line_max_len place_holder alignment APPEND color)
  set(empty_string "")
  if (ARGC GREATER_EQUAL 2)
    set(line_max_len ${ARGV1})
  else()
    set(line_max_len ${default_output_max_len})
  endif()

  if (ARGC GREATER_EQUAL 3)
    set(place_holder ${ARGV2})
  else()
    set(place_holder "-")
  endif()

  if (ARGC GREATER_EQUAL 4)
    set(alignment ${ARGV3})
  else()
    set(alignment "c")
  endif()

  if (ARGC GREATER_EQUAL 5)
    if(${ARGV4})
      set(APPEND echo_append)
    else()
      set(APPEND echo)
    endif()
  else()
    set(APPEND echo)
  endif()

  if (ARGC GREATER_EQUAL 6)
    if(${ARGV5})
      set(color ${ARGV5})
    else()
      set(color empty_string)
    endif()
  else()
    set(color empty_string)
  endif()

  string(LENGTH ${arg1}, len_arg1)
  math(EXPR extra_chars "${line_max_len} - ${len_arg1} + 1")

  if (alignment STREQUAL "c")
    if(len_arg1 EQUAL 1)
      string(REPEAT ${place_holder} ${line_max_len} sep)
      #message(NOTICE "${sep}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${sep}${ColorReset}")
    elseif(${len_arg1} GREATER ${line_max_len})
      #message(NOTICE "${arg1}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${arg1}${ColorReset}")
    elseif(${extra_chars} LESS_EQUAL 2)
      math(EXPR prev_s_len "${extra_chars} % 2")
      string(REPEAT " " ${prev_s_len} prev_s)
      math(EXPR after_s_len "${extra_chars} / 2")
      string(REPEAT " " ${after_s_len} after_s)
      #message(NOTICE "${prev_s}${arg1}${after_s}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${prev_s}${arg1}${after_s}${ColorReset}")
    else()
      math(EXPR extra_chars "${extra_chars} - 2")
      math(EXPR prev_s_len "${extra_chars} / 2")
      string(REPEAT ${place_holder} ${prev_s_len} prev_s)
      math(EXPR after_s_len "${extra_chars} / 2 + ${extra_chars} % 2")
      string(REPEAT ${place_holder} ${after_s_len} after_s)
      #message(NOTICE "${prev_s} ${arg1} ${after_s}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${prev_s} ${arg1} ${after_s}${ColorReset}")
    endif()
  elseif(alignment STREQUAL "l")
    if(len_arg1 EQUAL 1)
      string(REPEAT ${place_holder} ${line_max_len} sep)
      #message(NOTICE "${sep}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${sep}${ColorReset}")
    elseif(${len_arg1} GREATER ${line_max_len})
      #message(NOTICE "${arg1}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${arg1}${ColorReset}")
    elseif(${extra_chars} LESS_EQUAL 1)
      string(REPEAT " " ${extra_chars} after_s)
      #message(NOTICE "${arg1}${after_s}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${arg1}${after_s}${ColorReset}")
    else()
      math(EXPR extra_chars "${extra_chars} - 1")
      string(REPEAT ${place_holder} ${extra_chars} after_s)
      #message(NOTICE "${arg1} ${after_s}" APPEND)
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${arg1} ${after_s}${ColorReset}")
    endif()
  elseif(alignment STREQUAL "r")
    if(len_arg1 EQUAL 1)
      string(REPEAT ${place_holder} ${line_max_len} sep)
      #message(NOTICE "${sep}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${sep}${ColorReset}")
    elseif(${len_arg1} GREATER ${line_max_len})
      #message(NOTICE "${arg1}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${arg1}${ColorReset}")
    elseif(${extra_chars} LESS_EQUAL 1)
      string(REPEAT " " ${extra_chars} befor_s)
      #message(NOTICE "${befor_s}${arg1}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${befor_s}${arg1}${ColorReset}")
    else()
      math(EXPR extra_chars "${extra_chars} - 1")
      string(REPEAT ${place_holder} ${extra_chars} befor_s)
      #message(NOTICE "${befor_s} ${arg1}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E ${APPEND} "${${color}}${befor_s} ${arg1}${ColorReset}")
    endif()
  endif()
endfunction()

function(print_message_two_parts part1 part2 part1_line_max_len color)
  print_as_title(${part1} ${part1_line_max_len} " " "l" ON ${color})
  print_as_title(${part2} 0 " " "l" OFF ${color})
endfunction()

function(print_cmake_info color)

  set(first_part_len 36)
  print_as_title("" ${default_output_max_len} " " "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("Main info about CMake" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})

  print_message_two_parts("- CMake version"                       ": ${CMAKE_VERSION}"                  ${first_part_len} ${color})
  print_message_two_parts("- CMake generator"                     ": ${CMAKE_GENERATOR}"              ${first_part_len} ${color})
  print_message_two_parts("- Target CMake system name"            ": ${CMAKE_SYSTEM_NAME}"            ${first_part_len} ${color})
  print_message_two_parts("- Target CMake system processor"       ": ${CMAKE_SYSTEM_PROCESSOR}"       ${first_part_len} ${color})
  print_message_two_parts("- Target CMake system version"         ": ${CMAKE_SYSTEM_VERSION}"         ${first_part_len} ${color})
  print_message_two_parts("- Target CMake host system name"       ": ${CMAKE_HOST_SYSTEM_NAME}"       ${first_part_len} ${color})
  print_message_two_parts("- Target CMake host system processor"  ": ${CMAKE_HOST_SYSTEM_PROCESSOR}"  ${first_part_len} ${color})
  print_message_two_parts("- Target CMake host system version"    ": ${CMAKE_HOST_SYSTEM_VERSION}"    ${first_part_len} ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
endfunction()

function(print_build_info color)

  set(first_part_len 37)
  print_as_title("" ${default_output_max_len} " " "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("Main info about build" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})

  print_message_two_parts("- PROJECT_SOURCE_DIR"        ": ${PROJECT_SOURCE_DIR}"       ${first_part_len} ${color})
  print_message_two_parts("- PROJECT_BINARY_DIR"        ": ${PROJECT_BINARY_DIR}"       ${first_part_len} ${color})
  print_message_two_parts("- CMAKE_INSTALL_INCLUDEDIR"  ": ${CMAKE_INSTALL_INCLUDEDIR}" ${first_part_len} ${color})

  if(NOT(CMAKE_SYSTEM_NAME IN_LIST PROJECT_SUPPORTED_SYSTEMS))
    print_message_two_parts("- Target CMake system are not supported" ": ${CMAKE_SYSTEM_NAME}"          ${first_part_len} Red)
    print_message_two_parts("- Supported systems"                     ": ${PROJECT_SUPPORTED_SYSTEMS}"  ${first_part_len} Red)
  endif()
  print_message_two_parts("- CMake interprocedural optimization"  ": ${ipo_supported}" ${first_part_len} ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
endfunction()

function(print_system_info color)
  print_as_title("" ${default_output_max_len} " " "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("Main info about host system" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})

  cmake_host_system_information(RESULT system_info_HOSTNAME QUERY HOSTNAME)
  cmake_host_system_information(RESULT system_info_FQDN QUERY FQDN)
  cmake_host_system_information(RESULT system_info_TOTAL_VIRTUAL_MEMORY QUERY TOTAL_VIRTUAL_MEMORY)
  cmake_host_system_information(RESULT system_info_AVAILABLE_VIRTUAL_MEMORY QUERY AVAILABLE_VIRTUAL_MEMORY)
  cmake_host_system_information(RESULT system_info_TOTAL_PHYSICAL_MEMORY QUERY TOTAL_PHYSICAL_MEMORY)
  cmake_host_system_information(RESULT system_info_AVAILABLE_PHYSICAL_MEMORY QUERY AVAILABLE_PHYSICAL_MEMORY)
  cmake_host_system_information(RESULT system_info_OS_NAME QUERY OS_NAME)
  cmake_host_system_information(RESULT system_info_OS_RELEASE QUERY OS_RELEASE)
  cmake_host_system_information(RESULT system_info_OS_VERSION QUERY OS_VERSION)
  cmake_host_system_information(RESULT system_info_OS_PLATFORM QUERY OS_PLATFORM)
  cmake_host_system_information(RESULT system_info_PRETTY_NAME QUERY DISTRIB_PRETTY_NAME)
  cmake_host_system_information(RESULT system_info_DISTRO QUERY DISTRIB_INFO)

  set(first_part_len 41)
  print_message_two_parts("- Host system name"                      ": ${system_info_HOSTNAME}"                     ${first_part_len} ${color})
  print_message_two_parts("- Host system full domain name"          ": ${system_info_FQDN}"                         ${first_part_len} ${color})
  print_message_two_parts("- Host system total virtual memory"      ": ${system_info_TOTAL_VIRTUAL_MEMORY} MB"      ${first_part_len} ${color})
  print_message_two_parts("- Host system available virtual memory"  ": ${system_info_AVAILABLE_VIRTUAL_MEMORY} MB"  ${first_part_len} ${color})
  print_message_two_parts("- Host system total physical memory"     ": ${system_info_TOTAL_PHYSICAL_MEMORY} MB"     ${first_part_len} ${color})
  print_message_two_parts("- Host system available physical memory" ": ${system_info_AVAILABLE_PHYSICAL_MEMORY} MB" ${first_part_len} ${color})
  print_message_two_parts("- Host system OS name"                   ": ${system_info_OS_NAME}"                      ${first_part_len} ${color})
  print_message_two_parts("- Host system OS release"                ": ${system_info_OS_RELEASE}"                   ${first_part_len} ${color})
  print_message_two_parts("- Host system OS version"                ": ${system_info_OS_VERSION}"                   ${first_part_len} ${color})
  print_message_two_parts("- Host system OS platform"               ": ${system_info_OS_PLATFORM}"                  ${first_part_len} ${color})

  foreach(VAR IN LISTS system_info_DISTRO)
    print_message_two_parts("- ${VAR}" ": ${${VAR}}" ${first_part_len} ${color})
  endforeach()

  cmake_host_system_information(RESULT system_info_NUMBER_OF_LOGICAL_CORES QUERY NUMBER_OF_LOGICAL_CORES)
  cmake_host_system_information(RESULT system_info_NUMBER_OF_PHYSICAL_CORES QUERY NUMBER_OF_PHYSICAL_CORES)
  cmake_host_system_information(RESULT system_info_HAS_SERIAL_NUMBER QUERY HAS_SERIAL_NUMBER)
  cmake_host_system_information(RESULT system_info_PROCESSOR_SERIAL_NUMBER QUERY PROCESSOR_SERIAL_NUMBER)
  cmake_host_system_information(RESULT system_info_PROCESSOR_NAME QUERY PROCESSOR_NAME)
  cmake_host_system_information(RESULT system_info_PROCESSOR_DESCRIPTION QUERY PROCESSOR_DESCRIPTION)
  cmake_host_system_information(RESULT system_info_IS_64BIT QUERY IS_64BIT)
  cmake_host_system_information(RESULT system_info_HAS_FPU QUERY HAS_FPU)
  cmake_host_system_information(RESULT system_info_HAS_MMX QUERY HAS_MMX)
  cmake_host_system_information(RESULT system_info_HAS_MMX_PLUS QUERY HAS_MMX_PLUS)
  cmake_host_system_information(RESULT system_info_HAS_SSE QUERY HAS_SSE)
  cmake_host_system_information(RESULT system_info_HAS_SSE2 QUERY HAS_SSE2)
  cmake_host_system_information(RESULT system_info_HAS_SSE_FP QUERY HAS_SSE_FP)
  cmake_host_system_information(RESULT system_info_HAS_SSE_MMX QUERY HAS_SSE_MMX)
  cmake_host_system_information(RESULT system_info_HAS_AMD_3DNOW QUERY HAS_AMD_3DNOW)
  cmake_host_system_information(RESULT system_info_HAS_AMD_3DNOW_PLUS QUERY HAS_AMD_3DNOW_PLUS)
  cmake_host_system_information(RESULT system_info_HAS_IA64 QUERY HAS_IA64)

  print_message_two_parts("- Host system number of logical cores" ": ${system_info_NUMBER_OF_LOGICAL_CORES}" ${first_part_len} ${color})
  print_message_two_parts("- Host system number of physical cores" ": ${system_info_NUMBER_OF_PHYSICAL_CORES}" ${first_part_len} ${color})

  if(system_info_HAS_SERIAL_NUMBER)
    print_message_two_parts("- Host system processor serial number" ": ${system_info_PROCESSOR_SERIAL_NUMBER}" ${first_part_len} ${color})
  endif()

  print_message_two_parts("- Host system processor name"        ": ${system_info_PROCESSOR_NAME}"         ${first_part_len} ${color})
  print_message_two_parts("- Host system processor description"  ": ${system_info_PROCESSOR_DESCRIPTION}"  ${first_part_len} ${color})
  print_message_two_parts("- Host system processor is 64 bit"   ": ${system_info_IS_64BIT}"               ${first_part_len} ${color})
  print_message_two_parts("- Host system has FPU"               ": ${system_info_HAS_FPU}"                ${first_part_len} ${color})
  print_message_two_parts("- Host system has MMX"               ": ${system_info_HAS_MMX}"                ${first_part_len} ${color})
  print_message_two_parts("- Host system has MMX_PLUS"          ": ${system_info_HAS_MMX_PLUS}"           ${first_part_len} ${color})
  print_message_two_parts("- Host system has SSE"               ": ${system_info_HAS_SSE}"                ${first_part_len} ${color})
  print_message_two_parts("- Host system has SSE2"              ": ${system_info_HAS_SSE2}"               ${first_part_len} ${color})
  print_message_two_parts("- Host system has SSE_FP"            ": ${system_info_HAS_SSE_FP}"             ${first_part_len} ${color})
  print_message_two_parts("- Host system has SSE_MMX"           ": ${system_info_HAS_SSE_MMX}"            ${first_part_len} ${color})
  print_message_two_parts("- Host system has AMD_3DNOW"         ": ${system_info_HAS_AMD_3DNOW}"          ${first_part_len} ${color})
  print_message_two_parts("- Host system has AMD_3DNOW_PLUS"    ": ${system_info_HAS_AMD_3DNOW_PLUS}"     ${first_part_len} ${color})
  print_message_two_parts("- Host system has IA64"              ": ${system_info_HAS_IA64}"               ${first_part_len} ${color})
  print_message_two_parts("- Host system byte order for CXX"    ": ${CMAKE_CXX_BYTE_ORDER}"               ${first_part_len} ${color})
  
  if(ENABLE_COVERAGE)
    print_message_two_parts("- LCOV version: "                    ": ${LCOV_VERSION}"               ${first_part_len} ${color})
  endif()
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
endfunction()

# Avoid CMake dev-mode errors when printing cache/options that may be unset
# (e.g. Graph consumed via FetchContent before top-level sets *_INSTALL_CMAKEDIR).
function(_utils_print_kv_optional label_out var_name first_part_len color)
  if(DEFINED "${var_name}")
    print_message_two_parts("${label_out}" ": ${${var_name}}" ${first_part_len} ${color})
  else()
    print_message_two_parts("${label_out}" ": <unset>" ${first_part_len} ${color})
  endif()
endfunction()

function(print_project_info color)
  set(first_part_len 38)
  print_as_title("" ${default_output_max_len} " " "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("Project info" ${default_output_max_len} "-" "c" OFF ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})

  print_message_two_parts("- Project name"                          ": ${PROJECT_NAME}"         ${first_part_len} ${color})
  print_message_two_parts("- Project version"                       ": ${PROJECT_VERSION}"      ${first_part_len} ${color})
  print_message_two_parts("- Project url"                           ": ${PROJECT_HOMEPAGE_URL}" ${first_part_len} ${color})
  print_message_two_parts("- Project description"                   ": ${PROJECT_DESCRIPTION}"  ${first_part_len} ${color})
  print_message_two_parts("- Project source dir"                    ": ${PROJECT_SOURCE_DIR}"   ${first_part_len} ${color})
  _utils_print_kv_optional("- CircuitGenGenerator_DEVELOPER_MODE" "CircuitGenGenerator_DEVELOPER_MODE" ${first_part_len} ${color})
  _utils_print_kv_optional("- CircuitGenGenerator_BUILD_EXAMPLES" "CircuitGenGenerator_BUILD_EXAMPLES" ${first_part_len} ${color})
  _utils_print_kv_optional("- CircuitGenGenerator_INSTALL_CMAKEDIR" "CircuitGenGenerator_INSTALL_CMAKEDIR" ${first_part_len} ${color})
  _utils_print_kv_optional("- BUILD_MCSS_DOCS" "BUILD_MCSS_DOCS" ${first_part_len} ${color})
  _utils_print_kv_optional("- ENABLE_COVERAGE" "ENABLE_COVERAGE" ${first_part_len} ${color})
  _utils_print_kv_optional("- CMAKE_CXX_FLAGS_INIT" "CMAKE_CXX_FLAGS_INIT" ${first_part_len} ${color})
  _utils_print_kv_optional("- CMAKE_EXPORT_COMPILE_COMMANDS" "CMAKE_EXPORT_COMPILE_COMMANDS" ${first_part_len} ${color})
  _utils_print_kv_optional("- CMAKE_CXX_VISIBILITY_PRESET" "CMAKE_CXX_VISIBILITY_PRESET" ${first_part_len} ${color})
  _utils_print_kv_optional("- CMAKE_VISIBILITY_INLINES_HIDDEN" "CMAKE_VISIBILITY_INLINES_HIDDEN" ${first_part_len} ${color})
  _utils_print_kv_optional("- THREADS_PREFER_PTHREAD_FLAG" "THREADS_PREFER_PTHREAD_FLAG" ${first_part_len} ${color})
  if(DEFINED external_targets)
    list(JOIN external_targets ", " external_targets_string)
  else()
    set(external_targets_string "<unset>")
  endif()
  print_message_two_parts("- Project external targets"              ": ${external_targets_string}"   ${first_part_len} ${color})
  print_as_title("" ${default_output_max_len} "-" "c" OFF ${color})
endfunction()

# set_if_undefined(<variable> [<value>]...)
#
# Set variable if it is not defined.
macro(set_if_undefined variable)
    if(NOT DEFINED "${variable}")
        set("${variable}" ${ARGN})
    endif()
endmacro()

# win_copy_deps_to_target_dir(<target> [<target-dep>]...)
#
# Creates custom command to copy runtime dependencies to target's directory after building the target.
# Function does nothing if platform is not Windows and ignores all dependencies except shared libraries.
# On CMake 3.21 or newer, function uses TARGET_RUNTIME_DLLS generator expression to obtain list of runtime
# dependencies. Specified dependencies (if any) are still used to find and copy PDB files for debug builds.
function(win_copy_deps_to_target_dir target)
    if(NOT WIN32)
        return()
    endif()

    set(has_runtime_dll_genex NO)

    if(CMAKE_MAJOR_VERSION GREATER 3 OR CMAKE_MINOR_VERSION GREATER_EQUAL 21)
        set(has_runtime_dll_genex YES)

        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -P "${mylib_SOURCE_DIR}/cmake/silent_copy.cmake"
                "$<TARGET_RUNTIME_DLLS:${target}>" "$<TARGET_FILE_DIR:${target}>"
            COMMAND_EXPAND_LISTS)
    endif()

    foreach(dep ${ARGN})
        get_target_property(dep_type ${dep} TYPE)

        if(dep_type STREQUAL "SHARED_LIBRARY")
            if(NOT has_runtime_dll_genex)
                add_custom_command(TARGET ${target} POST_BUILD
                    COMMAND ${CMAKE_COMMAND} -P "${mylib_SOURCE_DIR}/cmake/silent_copy.cmake"
                        "$<TARGET_FILE:${dep}>" "$<TARGET_PDB_FILE:${dep}>" "$<TARGET_FILE_DIR:${target}>"
                    COMMAND_EXPAND_LISTS)
            else()
                add_custom_command(TARGET ${target} POST_BUILD
                    COMMAND ${CMAKE_COMMAND} -P "${mylib_SOURCE_DIR}/cmake/silent_copy.cmake"
                        "$<TARGET_PDB_FILE:${dep}>" "$<TARGET_FILE_DIR:${target}>"
                    COMMAND_EXPAND_LISTS)
            endif()
        endif()
    endforeach()
endfunction()